import os
import uuid
import json
import logging
from typing import Dict, Any, List
import urllib.parse
from firebase_admin import storage
import opendataloader_pdf

from app.services.ocr_service import OCRService

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Prepend brew's Java 17 path to the environment PATH so the underlying Java engine is found
JAVA_BIN_PATH = "/opt/homebrew/opt/openjdk@17/bin"
if JAVA_BIN_PATH not in os.environ["PATH"]:
    os.environ["PATH"] = f"{JAVA_BIN_PATH}:{os.environ['PATH']}"
    logger.info("Java bin path added to PATH environment variable.")

class PDFParserService:
    def __init__(self, static_dir: str, upload_dir: str):
        self.static_dir = static_dir
        self.upload_dir = upload_dir
        
        # Ensure directories exist
        os.makedirs(self.static_dir, exist_ok=True)
        os.makedirs(self.upload_dir, exist_ok=True)
        
    def parse(self, pdf_file_path: str) -> Dict[str, Any]:
        """
        Parses a PDF using OpenDataLoader, extracting text structure, layouts, tables, and images.
        
        Returns:
            A dictionary containing the parsed JSON structure with mapped image URLs.
        """
        task_id = str(uuid.uuid4())
        
        # Create output directories for JSON and images
        task_json_dir = os.path.join(self.upload_dir, task_id)
        task_image_dir = os.path.join(self.static_dir, "images", task_id)
        
        os.makedirs(task_json_dir, exist_ok=True)
        os.makedirs(task_image_dir, exist_ok=True)
        
        # Determine output file name (opendataloader names the output JSON based on the input PDF name)
        pdf_basename = os.path.basename(pdf_file_path)
        pdf_name_no_ext = os.path.splitext(pdf_basename)[0]
        expected_json_path = os.path.join(task_json_dir, f"{pdf_name_no_ext}.json")
        
        logger.info(f"Parsing PDF: {pdf_file_path}")
        logger.info(f"JSON output dir: {task_json_dir}")
        logger.info(f"Images output dir: {task_image_dir}")
        
        try:
            # Convert PDF to JSON and extract images
            opendataloader_pdf.convert(
                input_path=pdf_file_path,
                output_dir=task_json_dir,
                format="json",
                image_output="external",
                image_dir=task_image_dir
            )
            
            # Check if JSON file was successfully generated
            if not os.path.exists(expected_json_path):
                # Sometimes it might name it without spaces or clean up characters, or output.json
                # Let's check what files exist in the output directory
                files = os.listdir(task_json_dir)
                json_files = [f for f in files if f.endswith('.json')]
                if json_files:
                    expected_json_path = os.path.join(task_json_dir, json_files[0])
                else:
                    raise FileNotFoundError("Structured JSON file was not generated by OpenDataLoader.")
            
            # Read and parse the generated JSON file
            with open(expected_json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                
            # Process the items in JSON to update image paths to web URLs
            # Typically OpenDataLoader outputs a list of document elements (paragraphs, tables, images, etc.)
            processed_data = self._process_extracted_data(data, task_id)

            # --- OCR PIPELINE ---
            # Extract the actual document elements list from the processed data
            elements = []
            is_dict_root = isinstance(processed_data, dict)
            if is_dict_root:
                elements = processed_data.get("kids", [])
            elif isinstance(processed_data, list):
                elements = processed_data

            # Detect if the document is scanned (image-based PDF)
            is_scanned = OCRService.is_scanned_document(elements)
            
            if is_scanned:
                logger.info("Scanned PDF detected — running Tesseract OCR on images...")
                enriched_elements = OCRService.apply_ocr_to_images(
                    elements=elements,
                    static_dir=self.static_dir,
                )
                # Replace the elements in the processed data
                if is_dict_root:
                    processed_data["kids"] = enriched_elements
                else:
                    processed_data = enriched_elements
            else:
                logger.info("Digital PDF detected — skipping OCR.")
            # --- END OCR PIPELINE ---

            # Extract cover image (first page) using PyMuPDF
            cover_filename = f"{task_id}.png"
            covers_dir = os.path.join(self.static_dir, "covers")
            os.makedirs(covers_dir, exist_ok=True)
            cover_path = os.path.join(covers_dir, cover_filename)
            cover_url = None
            try:
                import fitz  # PyMuPDF
                doc = fitz.open(pdf_file_path)
                if len(doc) > 0:
                    page = doc[0]
                    # Render page to an image (PNG)
                    pix = page.get_pixmap(dpi=150)
                    pix.save(cover_path)
                    
                    # Upload cover to Firebase Storage
                    storage_path = f"covers/{cover_filename}"
                    cover_url = self._upload_to_firebase(cover_path, storage_path)
                doc.close()
                logger.info(f"Cover extracted and uploaded successfully for task {task_id}: {cover_url}")
            except Exception as cover_err:
                logger.error(f"Error extracting/uploading PDF cover: {cover_err}")

            return {
                "success": True,
                "task_id": task_id,
                "is_scanned": is_scanned,
                "cover_url": cover_url,
                "document": processed_data
            }
            
        except Exception as e:
            logger.exception("Error occurred while parsing the PDF")
            return {
                "success": False,
                "error": str(e)
            }
            
    def _upload_to_firebase(self, local_path: str, storage_path: str) -> str:
        """
        Sube un archivo local a Firebase Storage y retorna su URL pública de descarga.
        """
        bucket = storage.bucket()
        blob = bucket.blob(storage_path)
        blob.upload_from_filename(local_path)
        # Hacemos que sea legible (opcional si Firebase rules lo permiten, pero mejor usar el token)
        blob.make_public()
        
        # Generar URL de descarga formato Firebase
        encoded_path = urllib.parse.quote(blob.name, safe='')
        download_url = f"https://firebasestorage.googleapis.com/v0/b/{bucket.name}/o/{encoded_path}?alt=media"
        return download_url

    def _process_extracted_data(self, data: Any, task_id: str) -> Any:
        """
        Post-processes the JSON structure, changing absolute/local image filesystem paths
        to public Firebase Storage URL paths.
        """
        # If it's a list, process each element
        if isinstance(data, list):
            for item in data:
                if isinstance(item, dict):
                    # Check if this item is an image or contains an image reference
                    for key in ["image_path", "src", "path", "source"]:
                        if key in item and isinstance(item[key], str):
                            val = item[key]
                            # If it points to our local image directory
                            local_images_dir = os.path.join(self.static_dir, "images", task_id)
                            filename = os.path.basename(val)
                            local_path = os.path.join(local_images_dir, filename)
                            
                            if ("images/" in val or task_id in val) and os.path.exists(local_path):
                                storage_path = f"images/{task_id}/{filename}"
                                try:
                                    firebase_url = self._upload_to_firebase(local_path, storage_path)
                                    item[key] = firebase_url
                                except Exception as e:
                                    logger.error(f"Error subiendo imagen {filename} a Firebase: {e}")
                                    # Fallback (aunque en Render se romperá, mejor dejar vacío o local)
                                    item[key] = f"/static/images/{task_id}/{filename}"
            return data
            
        # If it's a dict, traverse recursively
        elif isinstance(data, dict):
            for k, v in data.items():
                if k in ["image_path", "src", "path", "source"] and isinstance(v, str):
                    filename = os.path.basename(v)
                    local_images_dir = os.path.join(self.static_dir, "images", task_id)
                    local_path = os.path.join(local_images_dir, filename)
                    
                    if os.path.exists(local_path):
                        storage_path = f"images/{task_id}/{filename}"
                        try:
                            data[k] = self._upload_to_firebase(local_path, storage_path)
                        except Exception as e:
                            logger.error(f"Error subiendo imagen {filename} a Firebase: {e}")
                            data[k] = f"/static/images/{task_id}/{filename}"
                else:
                    data[k] = self._process_extracted_data(v, task_id)
            return data
            
        return data
