import os
import uuid
import json
import logging
from typing import Dict, Any, List
import opendataloader_pdf

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Prepend brew's Java 17 path to the environment PATH so the underlying Java engine is found
JAVA_BIN_PATH = "/opt/homebrew/opt/openjdk@17/bin"
if JAVA_BIN_PATH not in os.environ["PATH"]:
    os.environ["PATH"] = f"{JAVA_BIN_PATH}:{os.environ['PATH']}"
    logger.info("Java bin path added to PATH environment variable.")

class PDFParserService:
    def __init__(self, static_dir: str, upload_dir: str):
        self.static_dir = static_dir
        self.upload_dir = upload_dir
        
        # Ensure directories exist
        os.makedirs(self.static_dir, exist_ok=True)
        os.makedirs(self.upload_dir, exist_ok=True)
        
    def parse(self, pdf_file_path: str) -> Dict[str, Any]:
        """
        Parses a PDF using OpenDataLoader, extracting text structure, layouts, tables, and images.
        
        Returns:
            A dictionary containing the parsed JSON structure with mapped image URLs.
        """
        task_id = str(uuid.uuid4())
        
        # Create output directories for JSON and images
        task_json_dir = os.path.join(self.upload_dir, task_id)
        task_image_dir = os.path.join(self.static_dir, "images", task_id)
        
        os.makedirs(task_json_dir, exist_ok=True)
        os.makedirs(task_image_dir, exist_ok=True)
        
        # Determine output file name (opendataloader names the output JSON based on the input PDF name)
        pdf_basename = os.path.basename(pdf_file_path)
        pdf_name_no_ext = os.path.splitext(pdf_basename)[0]
        expected_json_path = os.path.join(task_json_dir, f"{pdf_name_no_ext}.json")
        
        logger.info(f"Parsing PDF: {pdf_file_path}")
        logger.info(f"JSON output dir: {task_json_dir}")
        logger.info(f"Images output dir: {task_image_dir}")
        
        try:
            # Convert PDF to JSON and extract images
            opendataloader_pdf.convert(
                input_path=pdf_file_path,
                output_dir=task_json_dir,
                format="json",
                image_output="external",
                image_dir=task_image_dir
            )
            
            # Check if JSON file was successfully generated
            if not os.path.exists(expected_json_path):
                # Sometimes it might name it without spaces or clean up characters, or output.json
                # Let's check what files exist in the output directory
                files = os.listdir(task_json_dir)
                json_files = [f for f in files if f.endswith('.json')]
                if json_files:
                    expected_json_path = os.path.join(task_json_dir, json_files[0])
                else:
                    raise FileNotFoundError("Structured JSON file was not generated by OpenDataLoader.")
            
            # Read and parse the generated JSON file
            with open(expected_json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                
            # Process the items in JSON to update image paths to web URLs
            # Typically OpenDataLoader outputs a list of document elements (paragraphs, tables, images, etc.)
            processed_data = self._process_extracted_data(data, task_id)
            
            return {
                "success": True,
                "task_id": task_id,
                "document": processed_data
            }
            
        except Exception as e:
            logger.exception("Error occurred while parsing the PDF")
            return {
                "success": False,
                "error": str(e)
            }
            
    def _process_extracted_data(self, data: Any, task_id: str) -> Any:
        """
        Post-processes the JSON structure, changing absolute/local image filesystem paths
        to public URL paths.
        """
        # If it's a list, process each element
        if isinstance(data, list):
            for item in data:
                if isinstance(item, dict):
                    # Check if this item is an image or contains an image reference
                    # Depending on OpenDataLoader's schema, it could have fields like 'image_path', 'src', etc.
                    # We look for common patterns or fields that match file paths
                    for key in ["image_path", "src", "path", "source"]:
                        if key in item and isinstance(item[key], str):
                            val = item[key]
                            # If it points to our local image directory, rewrite it to static web URL
                            if "images/" in val or task_id in val or os.path.basename(val) in os.listdir(os.path.join(self.static_dir, "images", task_id)):
                                filename = os.path.basename(val)
                                item[key] = f"/static/images/{task_id}/{filename}"
            return data
            
        # If it's a dict (e.g. metadata or document container), traverse recursively
        elif isinstance(data, dict):
            for k, v in data.items():
                if k in ["image_path", "src", "path", "source"] and isinstance(v, str):
                    filename = os.path.basename(v)
                    data[k] = f"/static/images/{task_id}/{filename}"
                else:
                    data[k] = self._process_extracted_data(v, task_id)
            return data
            
        return data
